version: "3"

services:
    db:
        image: mysql
        container_name: it_inventory_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - it_inventory_data:/var/lib/mysql

volumes:
    it_inventory_data:
